# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyPets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyPets
  # Основная библиотека MapKit.
  pod ‘YandexMapKit’, ’3.5’ 
  # Дополнительные модули MapKit.
  # Удалите зависимости если ваше приложение не использует их.
  # pod ‘YandexMapKitDirections’, ’3.5’ 
  # pod ‘YandexMapKitPlaces’, ’3.5’ 
  # pod ‘YandexMapKitSearch’, ’3.5’ 
  # pod ‘YandexMapKitTransport’, ’3.5’

end
